# Generated by Django 3.2.9 on 2022-01-04 14:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likefrom',
            field=models.ManyToManyField(blank=True, related_name='likeform', to=settings.AUTH_USER_MODEL),
        ),
    ]
